Heroku style java install initial commit (#1)
* Heroku style java install initial commit

* added some debugging lines

* Source lines require bash

* added some debugging lines

* added some debugging lines - use heroku provided build dir

* build_dir is readonly

* build_dir is passed as an arg to bin/compile

* cleanup

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,25 +1,46 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 
-apt-get update
 
-# Install basics.
-apt install -y sudo
+if [[ "$(uname)" == "Darwin" ]]; then
+  echo "This script is only supported in Heroku dynos"
+  exit 1
+fi
 
-# Install JRE.
-# Here we specify the exact Java version, but the value should come from your repository.
-apt install -y openjdk-21-jre-headless
-echo "[Java Version]"
-java --version
+# Heroku build env passes 3 dirs to bin/compile
+BUILD_DIR="$1"
+CACHE_DIR="$2"
+ENV_DIR="$3"
 
-# Install AWS CLI to fetch Java jar.
-# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
-curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-unzip awscliv2.zip
-sudo ./aws/install
-echo "[AWS CLI Version]"
-aws --version
 
-# aws authenticate ... (and check access keys, secrets)
-# aws codeartifact ...
+# BUILD_DIR and CACHE_DIR are provided by Heroku's build env
+echo "BUILD_DIR is: $BUILD_DIR"
+
+install_java () {
+  # Initial cleanup
+  rm -rf /tmp/jvm.tgz /tmp/jre || true
+
+  # Create required dirs if they do not exist
+  mkdir -p /tmp/jre
+
+  # Fetch and Extract Heroku java installer
+  wget https://buildpack-registry.s3.us-east-1.amazonaws.com/buildpacks/heroku/jvm.tgz -O /tmp/jvm.tgz
+  tar -zxvf /tmp/jvm.tgz -C /tmp/jre/
+
+  # Default to Java 21 if file does not exist
+  # $REPO_ROOT/$ is mounted read-only, we should add this file to the repo
+  # if [ ! -f ${1}/system.properties ]; then
+  #    echo "java.runtime.version = 21" >> ${BUILD_DIR}/system.properties
+  # fi
+
+  # Install Java to ${BUILD_DIR}/ including .profile.d shell scripts which set JAVA_HOME etc
+  source /tmp/jre/bin/util
+  source /tmp/jre/bin/java
+  source /tmp/jre/opt/jdbc.sh
+
+  install_java_with_overlay "$1" "$2"
+
+}
+
+install_java "${BUILD_DIR}" "${CACHE_DIR}"
